CREATE TABLE products (
    id BIGINT NOT NULL AUTO_INCREMENT,
    vendor VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    website_url VARCHAR(500) NOT NULL,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
