INSERT INTO providers (
    slug,
    name,
    english_name,
    display_name,
    summary,
    description,
    logo_url,
    accent_color,
    categories,
    official_url,
    status,
    sort_order,
    verified_at
) VALUES
    (
        'deepseek',
        'DeepSeek',
        '深度求索',
        'DeepSeek · 深度求索',
        '提供面向个人用户的 AI 助手，以及供开发者和企业调用的模型 API。',
        'DeepSeek 的产品覆盖网页与移动端对话、复杂推理、代码辅助和开放平台 API。普通用户可以直接使用对话产品，开发者可以通过开放平台将模型能力接入自己的程序。',
        'https://www.deepseek.com/favicon.ico',
        '#4D6BFE',
        JSON_ARRAY('大模型', 'AI 助手', '开发平台'),
        'https://www.deepseek.com/',
        'active',
        10,
        '2026-07-12'
    ),
    (
        'moonshot',
        '月之暗面',
        'Moonshot AI',
        '月之暗面 · Kimi',
        '围绕 Kimi 提供研究、内容创作、办公、编程和开发者 API 产品。',
        '月之暗面以 Kimi 为主要产品品牌，覆盖面向个人用户的智能工作空间、桌面与浏览器工具、代码 Agent，以及供开发者集成模型能力的开放平台。',
        'https://statics.moonshot.cn/moonshot-ai/assets/static/kimi-icon.ByIGCGon.webp',
        '#111111',
        JSON_ARRAY('AI 助手', '编程工具', '开发平台'),
        'https://www.moonshot.ai/',
        'active',
        20,
        '2026-07-12'
    ),
    (
        'zhipu',
        '智谱 AI',
        'Zhipu AI',
        '智谱 AI · GLM / Z.ai',
        '围绕 GLM 模型提供个人助手、编程工具、模型 API 和智能体开发能力。',
        '智谱 AI 的产品体系包括面向个人用户的 Z.ai、面向开发者的 GLM 模型与开放平台，以及编程和智能体相关工具。模型能力覆盖文本、视觉、图像与视频等方向。',
        'https://www.zhipuai.cn/logo.svg',
        '#155EEF',
        JSON_ARRAY('大模型', '多模态', '开发平台'),
        'https://www.zhipuai.cn/',
        'active',
        30,
        '2026-07-12'
    ),
    (
        'alibaba',
        '阿里云',
        'Alibaba Cloud',
        '阿里云 · 通义 / 百炼',
        '通过通义和百炼提供个人 AI 产品、模型服务、编程工具与应用开发平台。',
        '阿里云的 AI 产品体系包括面向个人用户的通义、面向开发者的 Qwen Code，以及提供模型调用、评测、应用构建和企业服务的阿里云百炼。',
        'https://img.alicdn.com/tfs/TB1_ZXuNcfpK1RjSZFOXXa6nFXa-32-32.ico',
        '#FF6A00',
        JSON_ARRAY('云平台', '大模型', '开发平台'),
        'https://www.aliyun.com/product/bailian',
        'active',
        40,
        '2026-07-12'
    ),
    (
        'volcengine',
        '火山引擎',
        'Volcengine',
        '火山引擎 · 豆包 / 方舟',
        '提供豆包产品、火山方舟模型服务和 AgentKit 智能体开发平台。',
        '火山引擎的 AI 产品覆盖面向个人用户的豆包、提供模型推理与评测等服务的火山方舟，以及用于构建、部署和运维企业级智能体的 AgentKit。',
        'https://portal.volccdn.com/obj/volcfe/misc/favicon.png',
        '#1664FF',
        JSON_ARRAY('云平台', '多模态', 'Agent 平台'),
        'https://www.volcengine.com/',
        'active',
        50,
        '2026-07-12'
    ),
    (
        'baidu',
        '百度智能云',
        'Baidu AI Cloud',
        '百度智能云 · 文心 / 千帆',
        '提供文心模型、个人 AI 产品和以模型及 Agent 开发为核心的百度千帆平台。',
        '百度的 AI 产品体系包括面向个人用户的文小言，以及面向开发者和企业的百度千帆。千帆提供模型服务、Agent 开发、知识库、工具和企业级应用能力。',
        'https://bce.bdstatic.com/img/favicon.ico',
        '#2468F2',
        JSON_ARRAY('云平台', '大模型', 'Agent 平台'),
        'https://cloud.baidu.com/product-s/qianfan_home',
        'active',
        60,
        '2026-07-12'
    );
