INSERT INTO offerings (
    provider_id, slug, name, offering_type, summary, description, official_url,
    platforms, capabilities, pricing_mode, requires_install, requires_account,
    status, sort_order, verified_at
) VALUES
    ((SELECT id FROM providers WHERE slug = 'deepseek'), 'chat', 'DeepSeek Chat', 'AI 助手',
     '面向个人用户的网页与移动端对话入口。',
     '无需 API Key 即可使用，适合问答、长文阅读、复杂推理和代码辅助。',
     'https://chat.deepseek.com/', JSON_ARRAY('Web', 'iOS', 'Android'),
     JSON_ARRAY('对话', '推理', '文件阅读', '代码辅助'), '免费', FALSE, TRUE, 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'deepseek'), 'open-platform', 'DeepSeek 开放平台', '开发平台',
     '提供 API Key、模型调用、用量和计费管理。',
     '开发者可以通过兼容主流协议的 API，把 DeepSeek 模型接入后端服务和业务系统。',
     'https://platform.deepseek.com/', JSON_ARRAY('Web', 'API'),
     JSON_ARRAY('模型 API', '用量管理', '计费管理'), '按量', FALSE, TRUE, 'active', 20, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'moonshot'), 'kimi', 'Kimi', 'AI 助手',
     '集研究、文档、表格、演示和网站生成为一体的智能工作空间。',
     '面向普通用户处理问答、深度研究、内容创作和多步骤任务，主要能力直接集成在 Kimi 工作空间中。',
     'https://www.kimi.com/', JSON_ARRAY('Web', 'iOS', 'Android'),
     JSON_ARRAY('深度研究', '文档', '表格', '演示', '网站生成'), '混合', FALSE, TRUE, 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'moonshot'), 'kimi-work', 'Kimi Work', '桌面工具',
     '连接本地文件、网页和数据源的桌面 Agent。',
     '面向知识工作者，可处理本地资料、自动化计划任务，并在多个数据源之间完成研究与办公任务。',
     'https://www.kimi.com/products/', JSON_ARRAY('桌面端'),
     JSON_ARRAY('本地文件', 'Agent Swarm', '计划任务', '数据源连接'), '订阅', TRUE, TRUE, 'active', 20, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'moonshot'), 'kimi-code', 'Kimi Code', '编程工具',
     '运行在终端和 IDE 中的代码 Agent。',
     '可以读取代码仓库、修改多个文件并执行命令，适合真实软件工程任务。',
     'https://www.kimi.com/code/', JSON_ARRAY('Windows', 'macOS', 'Linux'),
     JSON_ARRAY('代码阅读', '文件修改', '命令执行', 'IDE 集成'), '订阅', TRUE, TRUE, 'active', 30, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'moonshot'), 'webbridge', 'Kimi WebBridge', '浏览器扩展',
     '让 Agent 在浏览器中点击、填写、导航和提取信息。',
     '作为浏览器扩展连接网页操作能力，可用于研究、信息整理和需要网页交互的自动化任务。',
     'https://www.kimi.com/products/', JSON_ARRAY('浏览器扩展'),
     JSON_ARRAY('网页操作', '信息提取', '浏览器自动化'), '混合', TRUE, TRUE, 'active', 40, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'moonshot'), 'platform', 'Kimi API 开放平台', '开发平台',
     '提供 Kimi 模型、官方工具和 API 接入能力。',
     '开发者可以创建 API Key，通过 HTTP 或兼容 OpenAI 的 SDK 调用 Kimi 模型。',
     'https://platform.kimi.com/', JSON_ARRAY('Web', 'API'),
     JSON_ARRAY('模型 API', '官方工具', '开发工作台'), '按量', FALSE, TRUE, 'active', 50, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'zhipu'), 'z-ai', 'Z.ai', 'AI 助手',
     '面向个人用户的对话、创作与开发能力入口。',
     '直接在网页中体验 GLM 模型能力，适合日常问答、内容生成和代码辅助。',
     'https://chat.z.ai/', JSON_ARRAY('Web'),
     JSON_ARRAY('对话', '创作', '代码辅助'), '混合', FALSE, TRUE, 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'zhipu'), 'zcode', 'ZCode', '编程工具',
     '面向长时间软件工程任务的 Agentic Development Environment。',
     '用于理解代码仓库、规划开发任务并持续执行多步骤工程工作。',
     'https://docs.bigmodel.cn/cn/coding-plan/tool/zcode', JSON_ARRAY('桌面端'),
     JSON_ARRAY('代码 Agent', '长程任务', '工程交付'), '订阅', TRUE, TRUE, 'active', 20, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'zhipu'), 'coding-plan', 'GLM Coding Plan', '编程订阅',
     '供受支持的交互式编程工具使用的模型订阅。',
     '使用专用凭证把 GLM 模型接入 Claude Code、OpenCode、Cline、Cursor 等工具，不等同于通用 API 余额。',
     'https://docs.bigmodel.cn/cn/coding-plan/overview', JSON_ARRAY('Windows', 'macOS', 'Linux'),
     JSON_ARRAY('编程订阅', '第三方工具接入'), '订阅', FALSE, TRUE, 'active', 30, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'zhipu'), 'open-platform', '智谱开放平台', '开发平台',
     '提供 GLM 模型 API、应用开发和企业服务。',
     '覆盖文本、视觉、图像和视频等模型，并提供智能体、知识库、评测和内容安全等平台能力。',
     'https://open.bigmodel.cn/', JSON_ARRAY('Web', 'API'),
     JSON_ARRAY('模型 API', '智能体', '知识库', '评测'), '按量', FALSE, TRUE, 'active', 40, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'alibaba'), 'tongyi', '通义', 'AI 助手',
     '面向个人用户的问答、搜索和内容创作入口。',
     '用户可以直接使用通义完成日常问答、信息整理、写作和效率任务。',
     'https://www.tongyi.com/', JSON_ARRAY('Web', '移动端'),
     JSON_ARRAY('对话', '搜索', '创作'), '混合', FALSE, TRUE, 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'alibaba'), 'qwen-code', 'Qwen Code', '编程工具',
     '开源的命令行代码 Agent。',
     '可在终端中读取和修改代码、执行命令，并通过百炼按量服务或 Coding Plan 完成认证。',
     'https://help.aliyun.com/zh/model-studio/qwen-code', JSON_ARRAY('Windows', 'macOS', 'Linux'),
     JSON_ARRAY('代码 Agent', '命令行', '开源'), '混合', TRUE, TRUE, 'active', 20, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'alibaba'), 'model-studio', '阿里云百炼', '开发平台',
     '提供模型调用、评测、应用构建和企业服务。',
     '集中管理通义千问及第三方模型，支持 API 调用、知识库、智能体应用、模型评测与企业级治理。',
     'https://bailian.console.aliyun.com/', JSON_ARRAY('Web', 'API'),
     JSON_ARRAY('模型 API', '智能体', '知识库', '模型评测'), '按量', FALSE, TRUE, 'active', 30, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'alibaba'), 'coding-plan', '百炼 Coding Plan', '编程订阅',
     '面向交互式 AI 编程工具的固定月费套餐。',
     '使用专用 API Key 和 Base URL 接入受支持的编程工具，与百炼通用按量 API 分开计费。',
     'https://help.aliyun.com/zh/model-studio/coding-plan', JSON_ARRAY('开发工具'),
     JSON_ARRAY('编程订阅', '多模型', '固定额度'), '订阅', FALSE, TRUE, 'active', 40, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'volcengine'), 'doubao', '豆包', 'AI 助手',
     '面向个人用户的对话、搜索、创作与多模态助手。',
     '提供网页、桌面和移动端入口，可用于问答、信息检索、内容创作和多模态任务。',
     'https://www.doubao.com/', JSON_ARRAY('Web', 'Windows', 'macOS', '移动端'),
     JSON_ARRAY('对话', '搜索', '创作', '多模态'), '混合', TRUE, TRUE, 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'volcengine'), 'ark', '火山方舟', '开发平台',
     '提供模型推理、评测、精调和应用模型服务。',
     '搭载豆包及多种模型，帮助开发者完成模型选择、调用、评测、精调和生产部署。',
     'https://www.volcengine.com/product/ark', JSON_ARRAY('Web', 'API'),
     JSON_ARRAY('模型推理', '模型评测', '模型精调'), '按量', FALSE, TRUE, 'active', 20, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'volcengine'), 'agentkit', 'AgentKit', 'Agent 平台',
     '用于构建、部署、运行和运维企业级 Agent。',
     '提供运行时、工具、记忆、知识库、身份安全、评测和全链路可观测等基础设施。',
     'https://www.volcengine.com/product/agentkit', JSON_ARRAY('云平台', 'API'),
     JSON_ARRAY('Agent 运行时', '工具', '记忆', '知识库', '评测'), '按量', FALSE, TRUE, 'active', 30, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'baidu'), 'wenxiaoyan', '文小言', 'AI 助手',
     '面向个人用户的 AI 搜索、问答与创作入口。',
     '结合百度信息服务提供日常问答、搜索、深度思考和内容创作能力。',
     'https://yiyan.baidu.com/', JSON_ARRAY('Web', '移动端'),
     JSON_ARRAY('AI 搜索', '对话', '创作'), '混合', FALSE, TRUE, 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'baidu'), 'qianfan', '百度千帆', '开发平台',
     '以模型服务和 Agent 开发为核心的一站式企业 AI 平台。',
     '提供模型调用、Agent 开发、知识库、工具与 MCP、模型精调和企业级服务。',
     'https://console.bce.baidu.com/qianfan/', JSON_ARRAY('Web', 'API', 'SDK'),
     JSON_ARRAY('模型服务', 'Agent 开发', '知识库', 'MCP', '模型精调'), '按量', FALSE, TRUE, 'active', 20, '2026-07-12');

INSERT INTO ai_models (
    provider_id, slug, name, api_model_id, model_family, model_type, summary,
    modalities, context_tokens, max_output_tokens, supports_thinking,
    supports_tool_calls, openai_compatible, official_url, status, sort_order, verified_at
) VALUES
    ((SELECT id FROM providers WHERE slug = 'deepseek'), 'deepseek-v4-flash', 'DeepSeek-V4-Flash', 'deepseek-v4-flash', 'DeepSeek V4', '文本模型',
     '兼顾速度、推理、编程和 Agent 任务。', JSON_ARRAY('文本'), 1000000, 384000, TRUE, TRUE, TRUE,
     'https://api-docs.deepseek.com/quick_start/pricing', 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'deepseek'), 'deepseek-v4-pro', 'DeepSeek-V4-Pro', 'deepseek-v4-pro', 'DeepSeek V4', '文本模型',
     '面向高难推理、编程和长程任务的高能力版本。', JSON_ARRAY('文本'), 1000000, 384000, TRUE, TRUE, TRUE,
     'https://api-docs.deepseek.com/quick_start/pricing', 'active', 20, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'moonshot'), 'kimi-k2-7-code', 'Kimi K2.7 Code', 'kimi-k2.7-code', 'Kimi K2', '代码模型',
     '面向编程 Agent 和长程软件工程任务的代码模型。', JSON_ARRAY('文本', '图片', '视频'), 256000, NULL, TRUE, TRUE, TRUE,
     'https://platform.kimi.com/docs/guide/start-using-kimi-api', 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'moonshot'), 'kimi-k2-6', 'Kimi K2.6', 'kimi-k2.6', 'Kimi K2', '多模态模型',
     '适合通用对话、Agent、视觉理解和复杂推理。', JSON_ARRAY('文本', '图片', '视频'), 256000, NULL, TRUE, TRUE, TRUE,
     'https://platform.kimi.com/docs/guide/start-using-kimi-api', 'active', 20, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'zhipu'), 'glm-5-2', 'GLM-5.2', 'glm-5.2', 'GLM-5', '文本模型',
     '面向复杂长程任务和工程交付的旗舰模型。', JSON_ARRAY('文本'), 1000000, 128000, TRUE, TRUE, TRUE,
     'https://docs.bigmodel.cn/cn/guide/start/model-overview', 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'zhipu'), 'glm-5v-turbo', 'GLM-5V-Turbo', 'glm-5v-turbo', 'GLM-5V', '多模态模型',
     '兼顾视觉理解、推理、代码生成和 Agent 工作流。', JSON_ARRAY('文本', '图片', '视频'), 200000, 128000, TRUE, TRUE, TRUE,
     'https://docs.bigmodel.cn/cn/guide/start/model-overview', 'active', 20, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'zhipu'), 'glm-image', 'GLM-Image', 'glm-image', 'GLM Image', '图像生成模型',
     '强调复杂指令遵循和中文文字渲染的图像生成模型。', JSON_ARRAY('文本', '图片'), NULL, NULL, FALSE, FALSE, FALSE,
     'https://docs.bigmodel.cn/cn/guide/start/model-overview', 'active', 30, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'alibaba'), 'qwen3-7-max', 'Qwen3.7-Max', 'qwen3.7-max', 'Qwen3', '文本模型',
     '面向复杂推理、Agent 和通用任务的旗舰模型。', JSON_ARRAY('文本'), 1000000, NULL, TRUE, TRUE, TRUE,
     'https://help.aliyun.com/zh/model-studio/models', 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'alibaba'), 'qwen3-7-plus', 'Qwen3.7-Plus', 'qwen3.7-plus', 'Qwen3', '多模态模型',
     '兼顾综合能力、视觉输入和工具使用。', JSON_ARRAY('文本', '图片'), NULL, NULL, TRUE, TRUE, TRUE,
     'https://help.aliyun.com/zh/model-studio/models', 'active', 20, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'alibaba'), 'qwen3-coder-plus', 'Qwen3-Coder-Plus', 'qwen3-coder-plus', 'Qwen3 Coder', '代码模型',
     '面向代码生成、修改和编程 Agent 的模型。', JSON_ARRAY('文本'), 1000000, NULL, TRUE, TRUE, TRUE,
     'https://help.aliyun.com/zh/model-studio/model-pricing', 'active', 30, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'volcengine'), 'doubao-2-1-pro', 'Doubao 2.1 Pro', NULL, 'Doubao', '多模态模型',
     '面向复杂推理、Agent 和多模态任务的豆包模型。', JSON_ARRAY('文本', '图片'), NULL, NULL, TRUE, TRUE, TRUE,
     'https://www.volcengine.com/docs/82379/1399008?lang=zh', 'active', 10, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'volcengine'), 'seedream-5', 'Seedream 5.0', NULL, 'Seedream', '图像生成模型',
     '面向图像生成与编辑场景的视觉创作模型。', JSON_ARRAY('文本', '图片'), NULL, NULL, FALSE, FALSE, FALSE,
     'https://www.volcengine.com/docs/82379/1399008?lang=zh', 'active', 20, '2026-07-12'),
    ((SELECT id FROM providers WHERE slug = 'volcengine'), 'seedance-2', 'Seedance 2.0', NULL, 'Seedance', '视频生成模型',
     '面向文本或图片驱动的视频生成场景。', JSON_ARRAY('文本', '图片', '视频'), NULL, NULL, FALSE, FALSE, FALSE,
     'https://www.volcengine.com/docs/82379/1399008?lang=zh', 'active', 30, '2026-07-12'),

    ((SELECT id FROM providers WHERE slug = 'baidu'), 'ernie-5-1', 'ERNIE 5.1', 'ERNIE-5.1', 'ERNIE', '文本模型',
     '面向理解、生成、逻辑推理和长上下文任务的文心模型。', JSON_ARRAY('文本'), 128000, NULL, TRUE, TRUE, FALSE,
     'https://cloud.baidu.com/doc/qianfan-docs/s/Jm8r1826a', 'active', 10, '2026-07-12');

INSERT INTO model_prices (
    model_id, region, currency, price_kind, amount, unit, min_context_tokens,
    max_context_tokens, conditions, effective_from, source_url, verified_at
) VALUES
    ((SELECT id FROM ai_models WHERE slug = 'deepseek-v4-flash'), '全球', 'USD', '缓存命中输入', 0.0028, '每百万 Tokens', NULL, NULL, NULL, '2026-07-12', 'https://api-docs.deepseek.com/quick_start/pricing', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'deepseek-v4-flash'), '全球', 'USD', '缓存未命中输入', 0.14, '每百万 Tokens', NULL, NULL, NULL, '2026-07-12', 'https://api-docs.deepseek.com/quick_start/pricing', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'deepseek-v4-flash'), '全球', 'USD', '输出', 0.28, '每百万 Tokens', NULL, NULL, NULL, '2026-07-12', 'https://api-docs.deepseek.com/quick_start/pricing', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'deepseek-v4-pro'), '全球', 'USD', '缓存命中输入', 0.003625, '每百万 Tokens', NULL, NULL, NULL, '2026-07-12', 'https://api-docs.deepseek.com/quick_start/pricing', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'deepseek-v4-pro'), '全球', 'USD', '缓存未命中输入', 0.435, '每百万 Tokens', NULL, NULL, NULL, '2026-07-12', 'https://api-docs.deepseek.com/quick_start/pricing', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'deepseek-v4-pro'), '全球', 'USD', '输出', 0.87, '每百万 Tokens', NULL, NULL, NULL, '2026-07-12', 'https://api-docs.deepseek.com/quick_start/pricing', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'ernie-5-1'), '中国内地', 'CNY', '输入', 0.004, '每千 Tokens', 0, 32000, NULL, '2026-05-21', 'https://cloud.baidu.com/doc/qianfan-docs/s/Jm8r1826a', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'ernie-5-1'), '中国内地', 'CNY', '输出', 0.018, '每千 Tokens', 0, 32000, NULL, '2026-05-21', 'https://cloud.baidu.com/doc/qianfan-docs/s/Jm8r1826a', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'ernie-5-1'), '中国内地', 'CNY', '输入', 0.006, '每千 Tokens', 32001, 128000, NULL, '2026-05-21', 'https://cloud.baidu.com/doc/qianfan-docs/s/Jm8r1826a', '2026-07-12'),
    ((SELECT id FROM ai_models WHERE slug = 'ernie-5-1'), '中国内地', 'CNY', '输出', 0.022, '每千 Tokens', 32001, 128000, NULL, '2026-05-21', 'https://cloud.baidu.com/doc/qianfan-docs/s/Jm8r1826a', '2026-07-12');

INSERT INTO subscription_plans (
    offering_id, name, region, currency, amount, billing_period, quota_summary,
    restrictions, source_url, status, effective_from, verified_at
) VALUES
    ((SELECT id FROM offerings WHERE provider_id = (SELECT id FROM providers WHERE slug = 'zhipu') AND slug = 'coding-plan'),
     'GLM Coding Plan', '中国内地', 'CNY', NULL, '月', '以购买页面当前套餐为准',
     '仅用于官方列出的交互式编程工具，不等同于通用模型 API 余额。',
     'https://docs.bigmodel.cn/cn/coding-plan/overview', 'active', '2026-07-12', '2026-07-12'),
    ((SELECT id FROM offerings WHERE provider_id = (SELECT id FROM providers WHERE slug = 'alibaba') AND slug = 'coding-plan'),
     '百炼 Coding Plan Pro', '中国内地', 'CNY', 200.00, '月', '按模型调用次数提供多周期额度',
     '仅限受支持的交互式 AI 编程工具；专用 API Key 与通用按量 API Key 不可混用。',
     'https://help.aliyun.com/zh/model-studio/coding-plan', 'active', '2026-07-12', '2026-07-12');
